name: Build and Push ComfyUI Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout 仓库
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      # 2️⃣ 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 3️⃣ 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t xiuzhenpeng/comfyui:${{ github.event.inputs.tag || 'latest' }} .

      # 4️⃣ 推送 Docker 镜像
      - name: Push Docker image
        run: |
          docker push xiuzhenpeng/comfyui:${{ github.event.inputs.tag || 'latest' }}
